#!/bin/sh

if [ "$1" = "" ]
then
	echo "usage: pykill <script>"
	exit
fi

for arg in "$@"
do
	process=`ps -A -o pid,cmd | grep -v grep | grep -v pykill | grep "$arg" | awk '{print $1}'`
	if [ "$process" != "" ]
	then
		# echo "killing $process"
        for p in $process
        do
            proc_filename="/proc/$p/exe"
            cmd_filename="/proc/$p/cmdline"
            echo "proc_filename:$proc_filename"
            exe_filename=$(readlink -f $proc_filename)
            echo "exe_filename:$exe_filename"
            if [ -n "$exe_filename" ]
            then
                is_python=$(echo "$exe_filename" | grep "$exe_filename")
                if [ -n "$is_python" ]
                then
                    cmd_line=$(cat $cmd_filename) 
                    echo "+killing $p $cmd_line"
                    kill $p
                fi
            fi
            
        done
		# kill $process
	fi
done

